### ISSUE TITLE
Add support for GitLab

### ISSUE THREAD

**Issue by tallesl** [rgrove/rawgit#135] opened 2016-11-28 20:22 UTC
I would love to see it supporting [gitlab.com](https://gitlab.com)...

**Comment by rgrove** [comment] 2016-11-28 20:30
Dupe of #49.

**Closed by rgrove** 2016-11-28 20:30 UTC

**Comment by tallesl** [comment] 2016-11-30 15:22
> ["This issue is about Bitbucket. Feel free to open a new issue for Gitlab, but please don't hijack this one. Thanks!"](https://github.com/rgrove/rawgit/issues/49#issuecomment-71405117)

**Comment by rgrove** [comment] 2016-11-30 18:11
Sorry, you're right. When I saw this, I thought, "I'm sure there was another issue about this," then found that one, read the first two comments, and assumed that was where I had already discussed GitLab support. I should've kept reading.

Anyway, my official answer on this is that I have no plans to add support for additional services. RawGit's traffic has already grown to a point where it's getting tricky to manage given the small amount of time I have to devote to it, and I don't want to increase that burden.

**Comment by neoascetic** [comment] 2016-11-30 18:24
@tallesl as you've probably seen in the #49, you may try out alternatives such as raw.githack.com or raweverything.dislocal.com
