### ISSUE TITLE
404 is cached by cdn.rawgit.com ?

### ISSUE THREAD

**Issue by luochen1990** [rgrove/rawgit#63] opened 2015-04-27 10:08 UTC
I visited https://cdn.rawgit.com/luochen1990/coffee-mate/v0.11.5/build/global.coffee.js before I push the tag, and got 404 as expected.  But after I pushed the tag [here](https://github.com/luochen1990/coffee-mate/blob/v0.11.5/build/global.coffee.js), cdn.rawgit.com still returns 404 ...
Is this a bug ? or what can I do for this ?

**Comment by rgrove** [comment] 2015-04-27 17:27
Looks like I recently introduced a change that causes errors to be cached just as long as successful responses. Oops! Will fix.

**Comment by rgrove** [comment] 2015-04-27 17:59
The root cause is now fixed, and I've purged the CDN cache to remove the cached 404. Note that you may also need to clear your browser cache to see the fresh file.

**Closed** 2015-04-27 17:58 UTC
Labels: bug

**Comment by luochen1990** [comment] 2015-04-28 03:11
thx for your quick fix!
